export enum AuthServiceMessageType {
    REQUEST_AUTH_USER = "REQUEST_AUTH_USER",
    CREATE_PLATFORM_ACCESS_PERMISSION = "CREATE_PLATFORM_ACCESS_PERMISION",
    PLATFORM_ACCESS_PERMISSION_CREATED = "PLATFORM_ACCESS_PERMISSION_CREATED"
}


