export enum AuthServiceMessageType {
    REQUEST_AUTH_USER = "REQUEST_AUTH_USER",
    CREATE_ACCESS_PERMISSION = "CREATE_ACCESS_PERMISSION",
    PLATFORM_ACCESS_PERMISSION_CREATED = "PLATFORM_ACCESS_PERMISSION_CREATED"
}

export enum CoreServiceMessageType {
    UPDATE_BUSINESS_REGISTRATION_STAGE = "UPDATE_BUSINESS_REGISTRATION_STAGE",
}


