export enum AuthServiceMessageType {
    REQUEST_AUTH_USER = "REQUEST_AUTH_USER",
    CREATE_ACCESS_PERMISSION = "CREATE_ACCESS_PERMISSION",
    PLATFORM_ACCESS_PERMISSION_CREATED = "PLATFORM_ACCESS_PERMISSION_CREATED",
    REVOKE_PLATFORM_ACCESS_PERMISSION_FROM_BUSINESS = "REVOKE_PLATFORM_ACCESS_PERMISSION_FROM_BUSINESS"
}

export enum CoreServiceMessageType {
    UPDATE_BUSINESS_REGISTRATION_STAGE = "UPDATE_BUSINESS_REGISTRATION_STAGE",

}

export enum SubscriptionServiceMessageType {
    CREATE_SUBSCRIPTION_PLAN = "CREATE_SUBSCRIPTION_PLAN",
    SUBSCRIPTION_PLAN_CREATED = "SUBSCRIPTION_PLAN_CREATED",
    PLATFORM_SUBSCRIPTION_CREATED_EVENT = "PLATFORM_SUBSCRIPTION_CREATED"
}


