export enum RoutingKey {
    SUBSCRIPTION_SERVICE_ROUTING_KEY = "SUBSCRIPTION_PUB_SUB",
    AUTH_SERVICE_ROUTING_KEY = "AUTH_PUB_SUB"
}

export enum ExchangeNames {
    SUBSCRIPTION_DIRECT_EXCHANGE = "SUBSCRIPTION_DIRECT_EXCHANGE",
    AUTH_DIRECT_EXCHANGE = "AUTH_DIRECT_EXCHANGE"
}

export enum AppMsgQueues {
    AUTH_SERVICE_QUEUE = "AUTH_SERVICE_QUEUE",
    AUTH_SERVICE_REQUEST_QUEUE = "AUTH_SERVICE_REQUEST_QUEUE",
    AUTH_SERVICE_REPLY_QUEUE = "AUTH_SERVICE_REPLY_QUEUE",

    SUBSCRITPION_SERVICE_QUEUE = "SUBSCRITPION_SERVICE_QUEUE",
    SUBSCRIPTION_SERVICE_REQUEST_QUEUE = "SUBSCRIPTION_SERVICE_REQUEST_QUEUE",
    SUBSCRIPTION_SERVICE_REPLY_QUEUE = "SUBSCRIPTION_SERVICE_REPLY_QUEUE"

}