export enum RoutingKey {
    SUBSCRIPTION_SERVICE_ROUTING_KEY = "SUBSCRIPTION_PUB_SUB",
    AUTH_SERVICE_ROUTING_KEY = "AUTH_PUB_SUB",
    CORE_SERVICE_ROUTING_KEY = "CORE_PUB_SUB",

    CORE_SERVICE_EVENT = "event.core.*",
    AUTH_SERVICE_EVENT = "event.auth.*",
    SUBSCRIPTION_SERVICE_EVENT = "event.subscription.*",

}

export enum ExchangeNames {
    SUBSCRIPTION_DIRECT_EXCHANGE = "SUBSCRIPTION_DIRECT_EXCHANGE",
    AUTH_DIRECT_EXCHANGE = "AUTH_DIRECT_EXCHANGE",
    CORE_DIRECT_EXCHANGE = "CORE_DIRECT_EXCHANGE",
}

export enum AppMsgQueues {
    AUTH_SERVICE_QUEUE = "AUTH_SERVICE_EVENT_QUEUE",
    AUTH_SERVICE_REQUEST_QUEUE = "AUTH_SERVICE_REQUEST_QUEUE",
    AUTH_SERVICE_REPLY_QUEUE = "AUTH_SERVICE_REPLY_QUEUE",


    SUBSCRITPION_SERVICE_QUEUE = "SUBSCRITPION_SERVICE_EVENT_QUEUE",
    SUBSCRIPTION_SERVICE_REQUEST_QUEUE = "SUBSCRIPTION_SERVICE_REQUEST_QUEUE",
    SUBSCRIPTION_SERVICE_REPLY_QUEUE = "SUBSCRIPTION_SERVICE_REPLY_QUEUE",

    CORE_SERVICE_EVENT_QUEUE = "CORE_SERVICE_EVENT_QUEUE",
    CORE_SERVICE_REQUEST_QUEUE = "CORE_SERVICE_REQUEST_QUEUE",
    CORE_SERVICE_REPLY_QUEUE = "CORE_SERVICE_REPLY_QUEUE",

    ORDER_SERVICE_EVENT_QUEUE = "ORDER_SERVICE_EVENT_QUEUE",
    ORDER_SERVICE_REQUEST_QUEUE = "ORDER_SERVICE_REQUEST_QUEUE",
    ORDER_SERVICE_REPLY_QUEUE = "ORDER_SERVICE_REPLY_QUEUE",
}

export enum ExchangeTopics {
    EVENT_TOPIC = "event.*",
}

