export enum AppResources {
    BUSINESS = 'BUSINESS',
    BRANCH = 'BRANCH',
    STAFF = 'STAFF',
    PRODUCT = 'PRODUCT',
    CUSTOMER = 'CUSTOMER',
    USER = 'USER',
    PLATFORM_SERVICES = 'PLATFORM_SERVICES',
    PLATFORM_SERVICE_SUBSCRIPTION = 'PLATFORM_SERVICE_SUBSCRIPTION',
}

export enum AppResourceAction {
    // Product



    // Branchh
    CREATE_BRANCH = 'CREATE_BRANCH',

}

export enum ProductResourceAction {
    CREATE_ONE_PRODUCTS = "CREATE_ONE_PRODUCT",
    CREATE_HUNDRED_PRODUCTS = 'CREATE_HUNDRED_PRODUCTS',
    CREATE_500_PRODUCT = "CREATE_FIVE_HUNDRED_PRODUCTS",
    CREATE_THOUSAND_PRODUCTS = "CREATE_THOUSAND_PRODUCTS",
}

export enum BranchResourceAction {
    CREATE_ONE_BRANCHES = 'CREATE_ONE_BRANCH',
    CREATE_FIVE_BRANCHES = 'CREATE_FIVE_BRANCHES',
    CREATE_TEN_BRANCHES = 'CREATE_TEN_BRANCHES',
    CREATE_TWENTY_BRANCHES = 'CREATE_TWENTY_BRANCH',
}

export enum SubscriptionResorceAction {
    CREATE_1_MEMBER = "CREATE_1_MEMBER",
    CREATE_5_MEMBER = "CREATE_5_MEMBER",
    CREATE_10_MEMBER = "CREATE_10_MEMBER",
    CREATE_20_MEMBER = "CREATE_20_MEMBER",
    CREATE_50_MEMBER = "CREATE_50_MEMBER",

    CREATE_10_GROUPS = "CREATE_10_GROUPS",
    CREATE_20_GROUPS = "CREATE_20_GROUPS",
} 